import { Prodotto } from "./shared/Prodotto";
export const PRODOTTI : Prodotto[] = [
    new Prodotto(1,"panino","Big Bro","../../assets/prodotti/panini/big-bro_isolated.png",5.69,"Veramente BIGG"),
    new Prodotto(2,"panino","Loco Burger","../../assets/prodotti//panini/burger-isolated.png",5.50, "Veramente LOCO"),
    new Prodotto(3,"panino","Loco Cheese Burger","../../assets/prodotti/panini/cheese-isolated.png",3.6, "Veramente LIGHT"),
    new Prodotto(4,"panino","Chicken Kebab","../../assets/prodotti/panini/chicken-kebab-isolated.png",3.6, "Veramente LIGHT"),
    new Prodotto(5,"panino","Double Cheese Burger","../../assets/prodotti/panini/double-cheese-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(6,"panino","Founders Selection Asiago","../../assets/prodotti/panini/founders-selection-asiago-isolated.png",3.6,"Veramente LIGHT, l'asiago preso dal monte dove si riposarono vacche d'oro al tramonto più ipnotico dell'anno"),
    new Prodotto(7,"panino","Founders Selection BBQ","../../assets/prodotti/panini/founders-selection-bbq-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(8,"panino","Founders Selection Chicken","../../assets/prodotti/panini/founders-selection-chicken-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(9,"panino","Big Chicken & Bacon","../../assets/prodotti/panini/gran-chicken-bacon-isolated.png",3.6,"Veramente INVITANTE"),
    new Prodotto(10,"panino","Only Big Pig","../../assets/prodotti/panini/gran-pig-isolated.png",3.6,"Veramente PORCO"),
    new Prodotto(11,"panino","Original Chicken","../../assets/prodotti/panini/original-chicken-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(12,"panino","Only Big Pig Kebab","../../assets/prodotti/panini/pig-kebab-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(13,"bibita","Acqua","../../assets/prodotti/bibite/acqua-lilla_isolated.png",3.6,"Veramente ACQUA"),
    new Prodotto(14,"bibita","Birra","../../assets/prodotti/bibite/birra_isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(15,"bibita","Caffè","../../assets/prodotti/bibite/caffe-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(16,"bibita","Coca Cola Zero","../../assets/prodotti/bibite/cocacola_zero-logo-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(17,"bibita","Coca Cola","../../assets/prodotti/bibite/cocacola-logo-isolated.png",3.6,"Veramente COCA COLA"),
    new Prodotto(18,"bibita","Fanta","../../assets/prodotti/bibite/fanta-logo-isolated.png",3.6,"Veramente FANTASTICA"),
    new Prodotto(19,"bibita","Lipton Lemon","../../assets/prodotti/bibite/logo-lipton-lemon-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(20,"bibita","Lipton Peach","../../assets/prodotti/bibite/logo-lipton-peach-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(21,"bibita","Sprite","../../assets/prodotti/bibite/sprite-logo-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(22,"bibita","Succo Mela","../../assets/prodotti/bibite/succo-mela_isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(23,"bibita","Tropicana","../../assets/prodotti/bibite/tropicana-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(24,"insalata","BANANA","../../assets/prodotti/panini/Banana-Single.jpg",5.69,"Veramente PLATANO"),
    new Prodotto(25,"insalata","Insalata Mista","../../assets/prodotti/insalate/insalata-mista-isolated.png",3.6,"Veramente MISTA"),
    new Prodotto(26,"insalata","Insalata Pollo Croccante","../../assets/prodotti/insalate/insalata-pollo-croccante-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(27,"insalata","Insalata Pollo Grigliato","../../assets/prodotti/insalate/insalata-pollo-grigliato-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(28,"insalata","Insalata Verde con Pomodori","../../assets/prodotti/insalate/insalata-verde-pomodori-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(29,"salsa","Salsa Ketchup","../../assets/prodotti/salse/ketchup_isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(30,"salsa","Salsa Maionese","../../assets/prodotti/salse/maionese_isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(31,"salsa","Salsa Agrodolce","../../assets/prodotti/salse/salsa-agrodolce_isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(32,"salsa","Salsa BBQ","../../assets/prodotti/salse/salsa-barbecue_isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(33,"salsa","Salsa Senape","../../assets/prodotti/salse/senape_isolated.png",3.6,"Veramente MALVAGIA"),
    new Prodotto(34,"sfiziosita","MDJ Chicken Nuggets","../../assets/prodotti/sfiziosita/pepite-asiago-speck-isolated.png",3.6,"Veramente LIGHT"),
    new Prodotto(35,"sfiziosita","Chicken Wings","../../assets/prodotti/sfiziosita/chicken-wings-isolated.png",3.6,"Veramente NON ALI"),
    new Prodotto(36,"sfiziosita","Pepite Asiago & Speck","../../assets/prodotti/sfiziosita/chicken-MDJnuggets-isolated.png",3.6,"Veramente NUGGETS"),
];